version: '3'
services:
  # MySQL database
  mysql:
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $template-webapp_DB_PASSWORD
      MYSQL_DATABASE: $template-webapp_DB_NAME

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  
  # API
  template-webapp-server:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: template-webapp-server
    environment:
      PORT: 4000
    ports:
      - 80:4000
    depends_on: 
      - mysql
    restart: always

volumes:
  mysql-volume:
