openapi: "3.0.0"
info:
  version: 1.0.0
  title: Stock Simulator API
servers:
  - url: http://localhost:4000
paths:
  /auth/login:
    post:
      summary: Login
      operationId: login
      tags:
        - pets
      responses:
        '200':
          description: Success
        '400':
          description: Error