openapi: "3.0.0"
info:
  version: 1.0.0
  title: Stock Simulator API
servers:
  - url: http://localhost:4000
tags:
  - name: auth
    description: Everything about authentication
paths:
  /api/auth/signin/:
    post:
      summary: Sign in the user
      operationId: signIn
      tags:
        - auth
      requestBody:
        description: Credentials of the user
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Error
        '500':
          description: Internal Error
  /api/auth/signup/:
    post:
      summary: Create a new account for the user
      operationId: signUp
      tags:
        - auth
      requestBody:
        description: Account informations
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Error
        '500':
          description: Internal Error
